import type {
  BodyRegion,
  Equipment,
  Exercise,
  ExerciseMeasure,
  ExperienceLevel,
  MovementPattern,
  MuscleGroup,
} from '../schemas/index.js';

/** Compact authoring shape; `ex()` fills in defaults to produce a full `Exercise`. */
interface ExerciseSeed {
  id: string;
  name: string;
  pattern: MovementPattern;
  primary: MuscleGroup[];
  secondary?: MuscleGroup[];
  equipment: Equipment[];
  level: ExperienceLevel;
  contra?: BodyRegion[];
  subs: string[];
  cues: string[];
  /** Default: `reps`. */
  measure?: ExerciseMeasure;
  /** Default: true unless cardio or using only bodyweight, a pull-up bar or bands. */
  loadable?: boolean;
  /** Default: false. */
  unilateral?: boolean;
  /** Default: false. See `Exercise.low_stimulus`. */
  lowStimulus?: boolean;
}

const NON_LOADABLE_EQUIPMENT: readonly Equipment[] = ['bodyweight', 'pullup_bar', 'bands'];

function ex(seed: ExerciseSeed): Exercise {
  const defaultLoadable =
    seed.pattern !== 'cardio' &&
    !seed.equipment.some((item) => NON_LOADABLE_EQUIPMENT.includes(item));
  return {
    id: seed.id,
    name: seed.name,
    pattern: seed.pattern,
    primary_muscles: seed.primary,
    secondary_muscles: seed.secondary ?? [],
    equipment: seed.equipment,
    level: seed.level,
    contraindication_tags: seed.contra ?? [],
    substitutes: seed.subs,
    cues: seed.cues,
    measure: seed.measure ?? 'reps',
    loadable: seed.loadable ?? defaultLoadable,
    unilateral: seed.unilateral ?? false,
    low_stimulus: seed.lowStimulus ?? false,
  };
}

const SQUAT: Exercise[] = [
  ex({
    id: 'bodyweight_squat',
    name: 'Bodyweight Squat',
    pattern: 'squat',
    primary: ['quads', 'glutes'],
    secondary: ['adductors', 'abs'],
    equipment: ['bodyweight'],
    level: 'beginner',
    contra: ['knee', 'hip'],
    subs: ['chair_squat', 'goblet_squat', 'leg_press'],
    cues: ['Feet shoulder-width apart', 'Sit back and down', 'Knees track over toes'],
  }),
  ex({
    id: 'chair_squat',
    name: 'Chair Squat (Sit-to-Stand)',
    pattern: 'squat',
    primary: ['quads', 'glutes'],
    equipment: ['bodyweight'],
    level: 'beginner',
    subs: ['bodyweight_squat', 'goblet_squat'],
    cues: ['Lightly touch the chair, do not drop', 'Drive up through the whole foot'],
  }),
  ex({
    id: 'wall_sit',
    name: 'Wall Sit',
    pattern: 'squat',
    primary: ['quads'],
    secondary: ['glutes'],
    equipment: ['bodyweight'],
    level: 'beginner',
    contra: ['knee'],
    subs: ['chair_squat', 'bodyweight_squat'],
    cues: ['Back flat against the wall', 'Thighs as close to parallel as comfortable'],
    measure: 'seconds',
  }),
  ex({
    id: 'jump_squat',
    name: 'Jump Squat',
    pattern: 'squat',
    primary: ['quads', 'glutes'],
    secondary: ['calves'],
    equipment: ['bodyweight'],
    level: 'intermediate',
    contra: ['knee', 'ankle', 'hip'],
    subs: ['bodyweight_squat', 'goblet_squat'],
    cues: ['Land softly with bent knees', 'Reset between reps if form slips'],
  }),
  ex({
    id: 'goblet_squat',
    name: 'Dumbbell Goblet Squat',
    pattern: 'squat',
    primary: ['quads', 'glutes'],
    secondary: ['adductors', 'abs'],
    equipment: ['dumbbells'],
    level: 'beginner',
    contra: ['knee', 'hip'],
    subs: ['bodyweight_squat', 'kettlebell_goblet_squat', 'dumbbell_front_squat', 'leg_press'],
    cues: ['Hold the dumbbell at your chest', 'Elbows inside the knees at the bottom', 'Chest up'],
  }),
  ex({
    id: 'dumbbell_front_squat',
    name: 'Dumbbell Front Squat',
    pattern: 'squat',
    primary: ['quads', 'glutes'],
    secondary: ['abs', 'upper_back'],
    equipment: ['dumbbells'],
    level: 'intermediate',
    contra: ['knee', 'wrist', 'hip'],
    subs: ['goblet_squat', 'barbell_front_squat'],
    cues: ['Dumbbells resting on the shoulders', 'Elbows high', 'Brace before each rep'],
  }),
  ex({
    id: 'kettlebell_goblet_squat',
    name: 'Kettlebell Goblet Squat',
    pattern: 'squat',
    primary: ['quads', 'glutes'],
    secondary: ['adductors', 'abs'],
    equipment: ['kettlebell'],
    level: 'beginner',
    contra: ['knee', 'hip'],
    subs: ['goblet_squat', 'bodyweight_squat'],
    cues: ['Hold the bell by the horns at your chest', 'Sit between your heels'],
  }),
  ex({
    id: 'barbell_back_squat',
    name: 'Barbell Back Squat',
    pattern: 'squat',
    primary: ['quads', 'glutes'],
    secondary: ['adductors', 'lower_back', 'abs'],
    equipment: ['barbell', 'rack'],
    level: 'intermediate',
    contra: ['knee', 'lower_back', 'shoulder', 'hip', 'neck'],
    subs: ['goblet_squat', 'leg_press', 'hack_squat', 'barbell_front_squat'],
    cues: [
      'Bar on the upper back',
      'Brace and break at hips and knees together',
      'Use safety pins',
    ],
  }),
  ex({
    id: 'barbell_front_squat',
    name: 'Barbell Front Squat',
    pattern: 'squat',
    primary: ['quads', 'glutes'],
    secondary: ['upper_back', 'abs'],
    equipment: ['barbell', 'rack'],
    level: 'advanced',
    contra: ['knee', 'wrist', 'lower_back', 'hip'],
    subs: ['barbell_back_squat', 'dumbbell_front_squat', 'goblet_squat'],
    cues: ['Bar on the front of the shoulders', 'Elbows up throughout', 'Stay upright'],
  }),
  ex({
    id: 'leg_press',
    name: 'Leg Press',
    pattern: 'squat',
    primary: ['quads', 'glutes'],
    secondary: ['adductors'],
    equipment: ['machine'],
    level: 'beginner',
    contra: ['knee', 'hip'],
    subs: ['goblet_squat', 'hack_squat'],
    cues: ['Lower back stays on the pad', 'Do not lock the knees at the top'],
  }),
  ex({
    id: 'hack_squat',
    name: 'Hack Squat Machine',
    pattern: 'squat',
    primary: ['quads'],
    secondary: ['glutes'],
    equipment: ['machine'],
    level: 'intermediate',
    contra: ['knee', 'hip'],
    subs: ['leg_press', 'barbell_back_squat'],
    cues: ['Shoulders under the pads', 'Control the descent'],
  }),
];

const LUNGE: Exercise[] = [
  ex({
    id: 'bodyweight_reverse_lunge',
    name: 'Reverse Lunge',
    pattern: 'lunge',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings', 'adductors'],
    equipment: ['bodyweight'],
    level: 'beginner',
    contra: ['knee', 'hip'],
    subs: ['bodyweight_split_squat', 'step_up', 'dumbbell_reverse_lunge'],
    cues: ['Step back, lower the back knee', 'Front shin stays roughly vertical'],
    unilateral: true,
  }),
  ex({
    id: 'bodyweight_split_squat',
    name: 'Split Squat',
    pattern: 'lunge',
    primary: ['quads', 'glutes'],
    secondary: ['adductors'],
    equipment: ['bodyweight'],
    level: 'beginner',
    contra: ['knee', 'hip'],
    subs: ['bodyweight_reverse_lunge', 'dumbbell_bulgarian_split_squat'],
    cues: ['Staggered stance, feet hip-width', 'Lower straight down'],
    unilateral: true,
  }),
  ex({
    id: 'step_up',
    name: 'Step-Up',
    pattern: 'lunge',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings'],
    equipment: ['bodyweight'],
    level: 'beginner',
    contra: ['knee', 'hip'],
    subs: ['dumbbell_step_up', 'bodyweight_reverse_lunge'],
    cues: ['Use a stair or sturdy box', 'Push through the top foot, not the bottom one'],
    unilateral: true,
  }),
  ex({
    id: 'lateral_lunge',
    name: 'Lateral Lunge',
    pattern: 'lunge',
    primary: ['adductors', 'glutes'],
    secondary: ['quads'],
    equipment: ['bodyweight'],
    level: 'intermediate',
    contra: ['knee', 'hip'],
    subs: ['bodyweight_split_squat', 'bodyweight_reverse_lunge'],
    cues: ['Step wide, sit back into one hip', 'Keep the other leg straight'],
    unilateral: true,
  }),
  ex({
    id: 'dumbbell_reverse_lunge',
    name: 'Dumbbell Reverse Lunge',
    pattern: 'lunge',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings', 'adductors'],
    equipment: ['dumbbells'],
    level: 'beginner',
    contra: ['knee', 'hip'],
    subs: ['bodyweight_reverse_lunge', 'dumbbell_walking_lunge', 'barbell_reverse_lunge'],
    cues: ['Dumbbells at your sides', 'Step back and lower under control'],
    unilateral: true,
  }),
  ex({
    id: 'dumbbell_walking_lunge',
    name: 'Dumbbell Walking Lunge',
    pattern: 'lunge',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings', 'adductors'],
    equipment: ['dumbbells'],
    level: 'intermediate',
    contra: ['knee', 'hip'],
    subs: ['dumbbell_reverse_lunge', 'bodyweight_reverse_lunge'],
    cues: ['Long, controlled steps', 'Torso tall'],
    unilateral: true,
  }),
  ex({
    id: 'dumbbell_bulgarian_split_squat',
    name: 'Dumbbell Bulgarian Split Squat',
    pattern: 'lunge',
    primary: ['quads', 'glutes'],
    secondary: ['adductors'],
    equipment: ['dumbbells', 'bench'],
    level: 'intermediate',
    contra: ['knee', 'hip'],
    subs: ['bodyweight_split_squat', 'dumbbell_reverse_lunge', 'barbell_split_squat'],
    cues: ['Rear foot on the bench', 'Most weight on the front leg'],
    unilateral: true,
  }),
  ex({
    id: 'dumbbell_step_up',
    name: 'Dumbbell Step-Up',
    pattern: 'lunge',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings'],
    equipment: ['dumbbells', 'bench'],
    level: 'beginner',
    contra: ['knee', 'hip'],
    subs: ['step_up', 'dumbbell_reverse_lunge'],
    cues: ['Whole foot on the bench', 'Stand fully tall at the top'],
    unilateral: true,
  }),
  ex({
    id: 'barbell_reverse_lunge',
    name: 'Barbell Reverse Lunge',
    pattern: 'lunge',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings', 'adductors', 'abs'],
    equipment: ['barbell', 'rack'],
    level: 'intermediate',
    contra: ['knee', 'lower_back', 'hip'],
    subs: ['dumbbell_reverse_lunge', 'barbell_split_squat'],
    cues: ['Bar on the upper back', 'Step back and keep the torso tall'],
    unilateral: true,
  }),
  ex({
    id: 'barbell_split_squat',
    name: 'Barbell Split Squat',
    pattern: 'lunge',
    primary: ['quads', 'glutes'],
    secondary: ['adductors'],
    equipment: ['barbell', 'rack'],
    level: 'intermediate',
    contra: ['knee', 'hip'],
    subs: ['barbell_reverse_lunge', 'dumbbell_bulgarian_split_squat'],
    cues: ['Set the stance before unracking', 'Lower straight down'],
    unilateral: true,
  }),
];

const HINGE: Exercise[] = [
  ex({
    id: 'glute_bridge',
    name: 'Glute Bridge',
    pattern: 'hinge',
    primary: ['glutes'],
    secondary: ['hamstrings'],
    equipment: ['bodyweight'],
    level: 'beginner',
    subs: ['single_leg_glute_bridge', 'dumbbell_hip_thrust', 'barbell_hip_thrust'],
    cues: ['Heels close to the hips', 'Squeeze the glutes at the top', 'Ribs down'],
  }),
  ex({
    id: 'single_leg_glute_bridge',
    name: 'Single-Leg Glute Bridge',
    pattern: 'hinge',
    primary: ['glutes'],
    secondary: ['hamstrings'],
    equipment: ['bodyweight'],
    level: 'beginner',
    subs: ['glute_bridge', 'dumbbell_hip_thrust'],
    cues: ['Keep the hips level', 'Drive through the heel'],
    unilateral: true,
  }),
  ex({
    id: 'bodyweight_good_morning',
    name: 'Bodyweight Good Morning',
    pattern: 'hinge',
    primary: ['hamstrings', 'glutes'],
    secondary: ['lower_back'],
    equipment: ['bodyweight'],
    level: 'beginner',
    contra: ['lower_back'],
    subs: ['glute_bridge', 'dumbbell_romanian_deadlift'],
    cues: ['Hands behind the head', 'Push the hips back with a flat back', 'Soft knees'],
  }),
  ex({
    id: 'bodyweight_single_leg_rdl',
    name: 'Single-Leg Romanian Deadlift (Bodyweight)',
    pattern: 'hinge',
    primary: ['hamstrings', 'glutes'],
    secondary: ['abs'],
    equipment: ['bodyweight'],
    level: 'intermediate',
    contra: ['hip', 'lower_back'],
    subs: ['dumbbell_single_leg_rdl', 'bodyweight_good_morning'],
    cues: ['Hinge on one leg, the other leg reaches back', 'Hips square to the floor'],
    unilateral: true,
  }),
  ex({
    id: 'dumbbell_romanian_deadlift',
    name: 'Dumbbell Romanian Deadlift',
    pattern: 'hinge',
    primary: ['hamstrings', 'glutes'],
    secondary: ['lower_back', 'forearms'],
    equipment: ['dumbbells'],
    level: 'beginner',
    contra: ['lower_back', 'hip'],
    subs: ['bodyweight_good_morning', 'dumbbell_single_leg_rdl', 'barbell_romanian_deadlift'],
    cues: [
      'Dumbbells slide down the thighs',
      'Hips back, flat back',
      'Stop when hamstrings are tight',
    ],
  }),
  ex({
    id: 'dumbbell_single_leg_rdl',
    name: 'Dumbbell Single-Leg Romanian Deadlift',
    pattern: 'hinge',
    primary: ['hamstrings', 'glutes'],
    secondary: ['abs'],
    equipment: ['dumbbells'],
    level: 'intermediate',
    contra: ['lower_back', 'hip'],
    subs: ['bodyweight_single_leg_rdl', 'dumbbell_romanian_deadlift'],
    cues: ['Dumbbell in the opposite hand', 'Move slowly and keep balance'],
    unilateral: true,
  }),
  ex({
    id: 'dumbbell_hip_thrust',
    name: 'Dumbbell Hip Thrust',
    pattern: 'hinge',
    primary: ['glutes'],
    secondary: ['hamstrings'],
    equipment: ['dumbbells', 'bench'],
    level: 'beginner',
    contra: ['hip'],
    subs: ['glute_bridge', 'barbell_hip_thrust'],
    cues: ['Upper back on the bench', 'Dumbbell on the hips', 'Chin tucked, full lockout'],
  }),
  ex({
    id: 'barbell_deadlift',
    name: 'Barbell Deadlift',
    pattern: 'hinge',
    primary: ['hamstrings', 'glutes', 'lower_back'],
    secondary: ['quads', 'traps', 'forearms'],
    equipment: ['barbell'],
    level: 'intermediate',
    contra: ['lower_back', 'hip'],
    subs: ['barbell_romanian_deadlift', 'dumbbell_romanian_deadlift', 'kettlebell_swing'],
    cues: ['Bar over mid-foot', 'Brace, then push the floor away', 'Bar stays close to the legs'],
  }),
  ex({
    id: 'barbell_romanian_deadlift',
    name: 'Barbell Romanian Deadlift',
    pattern: 'hinge',
    primary: ['hamstrings', 'glutes'],
    secondary: ['lower_back', 'forearms'],
    equipment: ['barbell'],
    level: 'intermediate',
    contra: ['lower_back', 'hip'],
    subs: ['dumbbell_romanian_deadlift', 'barbell_deadlift', 'cable_pull_through'],
    cues: ['Start standing, push the hips back', 'Flat back, bar close'],
  }),
  ex({
    id: 'barbell_hip_thrust',
    name: 'Barbell Hip Thrust',
    pattern: 'hinge',
    primary: ['glutes'],
    secondary: ['hamstrings'],
    equipment: ['barbell', 'bench'],
    level: 'intermediate',
    contra: ['hip'],
    subs: ['dumbbell_hip_thrust', 'glute_bridge'],
    cues: ['Pad the bar', 'Shins vertical at the top', 'Do not over-arch the lower back'],
  }),
  ex({
    id: 'kettlebell_swing',
    name: 'Kettlebell Swing',
    pattern: 'hinge',
    primary: ['glutes', 'hamstrings'],
    secondary: ['lower_back', 'abs', 'forearms'],
    equipment: ['kettlebell'],
    level: 'intermediate',
    contra: ['lower_back', 'hip'],
    subs: ['dumbbell_romanian_deadlift', 'cable_pull_through'],
    cues: ['Hinge, do not squat', 'Snap the hips to float the bell', 'Arms stay relaxed'],
  }),
  ex({
    id: 'back_extension',
    name: 'Back Extension (45-Degree)',
    pattern: 'hinge',
    primary: ['glutes', 'hamstrings'],
    secondary: ['lower_back'],
    equipment: ['machine'],
    level: 'beginner',
    contra: ['lower_back'],
    subs: ['bodyweight_good_morning', 'glute_bridge'],
    cues: ['Pad just below the hip crease', 'Hinge at the hips, stop at a straight line'],
  }),
  ex({
    id: 'cable_pull_through',
    name: 'Cable Pull-Through',
    pattern: 'hinge',
    primary: ['glutes'],
    secondary: ['hamstrings'],
    equipment: ['cable'],
    level: 'beginner',
    subs: ['glute_bridge', 'kettlebell_swing', 'dumbbell_romanian_deadlift'],
    cues: ['Face away from the cable', 'Hips back, then squeeze forward'],
  }),
];

const PUSH_H: Exercise[] = [
  ex({
    id: 'push_up',
    name: 'Push-Up',
    pattern: 'push_h',
    primary: ['chest', 'triceps'],
    secondary: ['front_delts', 'abs'],
    equipment: ['bodyweight'],
    level: 'beginner',
    contra: ['wrist', 'shoulder'],
    subs: ['incline_push_up', 'knee_push_up', 'dumbbell_bench_press'],
    cues: [
      'Body in one straight line',
      'Elbows about 45 degrees from the body',
      'Chest to the floor',
    ],
  }),
  ex({
    id: 'incline_push_up',
    name: 'Incline Push-Up',
    pattern: 'push_h',
    primary: ['chest', 'triceps'],
    secondary: ['front_delts'],
    equipment: ['bodyweight'],
    level: 'beginner',
    contra: ['wrist'],
    subs: ['push_up', 'knee_push_up', 'dumbbell_floor_press'],
    cues: ['Hands on a table, counter or wall', 'Lower the chest to the edge'],
  }),
  ex({
    id: 'knee_push_up',
    name: 'Knee Push-Up',
    pattern: 'push_h',
    primary: ['chest', 'triceps'],
    secondary: ['front_delts'],
    equipment: ['bodyweight'],
    level: 'beginner',
    contra: ['wrist', 'knee'],
    subs: ['incline_push_up', 'push_up'],
    cues: ['Straight line from knees to head', 'Pad under the knees'],
  }),
  ex({
    id: 'dumbbell_bench_press',
    name: 'Dumbbell Bench Press',
    pattern: 'push_h',
    primary: ['chest'],
    secondary: ['triceps', 'front_delts'],
    equipment: ['dumbbells', 'bench'],
    level: 'beginner',
    contra: ['shoulder'],
    subs: ['dumbbell_floor_press', 'push_up', 'barbell_bench_press', 'machine_chest_press'],
    cues: ['Shoulder blades pulled back', 'Lower to chest level', 'Press up and slightly in'],
  }),
  ex({
    id: 'dumbbell_floor_press',
    name: 'Dumbbell Floor Press',
    pattern: 'push_h',
    primary: ['chest', 'triceps'],
    secondary: ['front_delts'],
    equipment: ['dumbbells'],
    level: 'beginner',
    subs: ['dumbbell_bench_press', 'push_up'],
    cues: ['Lie on the floor, knees bent', 'Pause with the upper arms on the floor'],
  }),
  ex({
    id: 'dumbbell_incline_press',
    name: 'Incline Dumbbell Press',
    pattern: 'push_h',
    primary: ['chest', 'front_delts'],
    secondary: ['triceps'],
    equipment: ['dumbbells', 'bench'],
    level: 'beginner',
    contra: ['shoulder'],
    subs: ['dumbbell_bench_press', 'incline_barbell_bench_press'],
    cues: ['Bench at 30-45 degrees', 'Lower to the upper chest'],
  }),
  ex({
    id: 'barbell_bench_press',
    name: 'Barbell Bench Press',
    pattern: 'push_h',
    primary: ['chest'],
    secondary: ['triceps', 'front_delts'],
    equipment: ['barbell', 'bench', 'rack'],
    level: 'intermediate',
    contra: ['shoulder'],
    subs: ['dumbbell_bench_press', 'machine_chest_press', 'push_up'],
    cues: [
      'Use a spotter or safety arms',
      'Feet planted, shoulder blades set',
      'Touch the lower chest',
    ],
  }),
  ex({
    id: 'incline_barbell_bench_press',
    name: 'Incline Barbell Bench Press',
    pattern: 'push_h',
    primary: ['chest', 'front_delts'],
    secondary: ['triceps'],
    equipment: ['barbell', 'bench', 'rack'],
    level: 'intermediate',
    contra: ['shoulder'],
    subs: ['dumbbell_incline_press', 'barbell_bench_press'],
    cues: ['Bench at 30 degrees', 'Bar touches the upper chest'],
  }),
  ex({
    id: 'machine_chest_press',
    name: 'Machine Chest Press',
    pattern: 'push_h',
    primary: ['chest'],
    secondary: ['triceps', 'front_delts'],
    equipment: ['machine'],
    level: 'beginner',
    contra: ['shoulder'],
    subs: ['dumbbell_bench_press', 'push_up'],
    cues: ['Handles at mid-chest height', 'Do not let the shoulders roll forward'],
  }),
];

const PUSH_V: Exercise[] = [
  ex({
    id: 'incline_pike_push_up',
    name: 'Incline Pike Push-Up',
    pattern: 'push_v',
    primary: ['front_delts', 'triceps'],
    secondary: ['side_delts'],
    equipment: ['bodyweight'],
    level: 'beginner',
    contra: ['shoulder', 'wrist'],
    subs: ['pike_push_up', 'dumbbell_overhead_press'],
    cues: ['Hands on a sturdy chair or step', 'Hips high, head moves forward of the hands'],
  }),
  ex({
    id: 'pike_push_up',
    name: 'Pike Push-Up',
    pattern: 'push_v',
    primary: ['front_delts', 'triceps'],
    secondary: ['side_delts'],
    equipment: ['bodyweight'],
    level: 'intermediate',
    contra: ['shoulder', 'wrist', 'neck'],
    subs: ['incline_pike_push_up', 'dumbbell_overhead_press'],
    cues: ['Hips high, inverted V', 'Lower the head toward the floor between the hands'],
  }),
  ex({
    id: 'dumbbell_overhead_press',
    name: 'Standing Dumbbell Overhead Press',
    pattern: 'push_v',
    primary: ['front_delts'],
    secondary: ['triceps', 'side_delts', 'abs'],
    equipment: ['dumbbells'],
    level: 'beginner',
    contra: ['shoulder', 'lower_back'],
    subs: ['seated_dumbbell_shoulder_press', 'pike_push_up', 'barbell_overhead_press'],
    cues: ['Squeeze glutes and brace', 'Press straight overhead', 'Do not lean back'],
  }),
  ex({
    id: 'seated_dumbbell_shoulder_press',
    name: 'Seated Dumbbell Shoulder Press',
    pattern: 'push_v',
    primary: ['front_delts'],
    secondary: ['triceps', 'side_delts'],
    equipment: ['dumbbells', 'bench'],
    level: 'beginner',
    contra: ['shoulder'],
    subs: ['dumbbell_overhead_press', 'machine_shoulder_press'],
    cues: ['Bench upright', 'Lower to ear level', 'Back stays on the pad'],
  }),
  ex({
    id: 'dumbbell_arnold_press',
    name: 'Arnold Press',
    pattern: 'push_v',
    primary: ['front_delts', 'side_delts'],
    secondary: ['triceps'],
    equipment: ['dumbbells'],
    level: 'intermediate',
    contra: ['shoulder'],
    subs: ['dumbbell_overhead_press', 'seated_dumbbell_shoulder_press'],
    cues: ['Start palms facing you', 'Rotate as you press'],
  }),
  ex({
    id: 'half_kneeling_dumbbell_press',
    name: 'Half-Kneeling Single-Arm Dumbbell Press',
    pattern: 'push_v',
    primary: ['front_delts'],
    secondary: ['triceps', 'abs', 'obliques'],
    equipment: ['dumbbells'],
    level: 'beginner',
    contra: ['shoulder'],
    subs: ['dumbbell_overhead_press', 'landmine_press'],
    cues: ['Kneel on the same side as the working arm', 'Ribs down, press up'],
    unilateral: true,
  }),
  ex({
    id: 'barbell_overhead_press',
    name: 'Barbell Overhead Press',
    pattern: 'push_v',
    primary: ['front_delts', 'triceps'],
    secondary: ['side_delts', 'abs', 'upper_back'],
    equipment: ['barbell', 'rack'],
    level: 'intermediate',
    contra: ['shoulder', 'lower_back'],
    subs: ['dumbbell_overhead_press', 'machine_shoulder_press'],
    cues: ['Bar starts on the front of the shoulders', 'Head through once the bar passes'],
  }),
  ex({
    id: 'machine_shoulder_press',
    name: 'Machine Shoulder Press',
    pattern: 'push_v',
    primary: ['front_delts'],
    secondary: ['triceps', 'side_delts'],
    equipment: ['machine'],
    level: 'beginner',
    contra: ['shoulder'],
    subs: ['seated_dumbbell_shoulder_press', 'barbell_overhead_press'],
    cues: ['Handles at shoulder height', 'Press without shrugging'],
  }),
  ex({
    id: 'landmine_press',
    name: 'Landmine Press',
    pattern: 'push_v',
    primary: ['front_delts'],
    secondary: ['chest', 'triceps', 'abs'],
    equipment: ['barbell'],
    level: 'beginner',
    subs: ['half_kneeling_dumbbell_press', 'machine_shoulder_press'],
    cues: ['Bar end anchored in a corner or landmine', 'Press up and forward'],
    unilateral: true,
  }),
];

const PULL_H: Exercise[] = [
  ex({
    id: 'doorframe_row',
    name: 'Doorframe Row',
    pattern: 'pull_h',
    primary: ['upper_back', 'lats'],
    secondary: ['biceps', 'rear_delts'],
    equipment: ['bodyweight'],
    level: 'beginner',
    subs: ['prone_superman_row', 'one_arm_dumbbell_row', 'inverted_row'],
    cues: ['Grip a solid door frame', 'Lean back, then pull the chest to the frame'],
  }),
  ex({
    id: 'prone_superman_row',
    name: 'Prone Superman Row',
    pattern: 'pull_h',
    primary: ['upper_back', 'rear_delts'],
    secondary: ['lower_back'],
    equipment: ['bodyweight'],
    level: 'beginner',
    contra: ['lower_back'],
    subs: ['doorframe_row', 'chest_supported_dumbbell_row'],
    cues: ['Lie face down, arms forward', 'Lift the chest slightly and pull elbows to the ribs'],
    lowStimulus: true,
  }),
  ex({
    id: 'one_arm_dumbbell_row',
    name: 'One-Arm Dumbbell Row',
    pattern: 'pull_h',
    primary: ['lats', 'upper_back'],
    secondary: ['biceps', 'rear_delts'],
    equipment: ['dumbbells', 'bench'],
    level: 'beginner',
    subs: ['dumbbell_bent_over_row', 'seated_cable_row', 'doorframe_row'],
    cues: ['Hand and knee on the bench', 'Pull the dumbbell to the hip', 'No torso twist'],
    unilateral: true,
  }),
  ex({
    id: 'dumbbell_bent_over_row',
    name: 'Dumbbell Bent-Over Row',
    pattern: 'pull_h',
    primary: ['upper_back', 'lats'],
    secondary: ['biceps', 'rear_delts', 'lower_back'],
    equipment: ['dumbbells'],
    level: 'intermediate',
    contra: ['lower_back'],
    subs: ['one_arm_dumbbell_row', 'chest_supported_dumbbell_row', 'barbell_bent_over_row'],
    cues: ['Hinge to about 45 degrees', 'Pull the elbows back'],
  }),
  ex({
    id: 'chest_supported_dumbbell_row',
    name: 'Chest-Supported Dumbbell Row',
    pattern: 'pull_h',
    primary: ['upper_back', 'lats'],
    secondary: ['rear_delts', 'biceps'],
    equipment: ['dumbbells', 'bench'],
    level: 'beginner',
    subs: ['one_arm_dumbbell_row', 'machine_chest_supported_row'],
    cues: ['Chest on an incline bench', 'Squeeze the shoulder blades together'],
  }),
  ex({
    id: 'renegade_row',
    name: 'Renegade Row',
    pattern: 'pull_h',
    primary: ['upper_back', 'lats'],
    secondary: ['abs', 'obliques', 'biceps'],
    equipment: ['dumbbells'],
    level: 'advanced',
    contra: ['wrist', 'shoulder', 'lower_back'],
    subs: ['one_arm_dumbbell_row', 'dumbbell_bent_over_row'],
    cues: ['Plank on the dumbbells, feet wide', 'Row without rotating the hips'],
    unilateral: true,
  }),
  ex({
    id: 'barbell_bent_over_row',
    name: 'Barbell Bent-Over Row',
    pattern: 'pull_h',
    primary: ['upper_back', 'lats'],
    secondary: ['biceps', 'rear_delts', 'lower_back'],
    equipment: ['barbell'],
    level: 'intermediate',
    contra: ['lower_back'],
    subs: ['dumbbell_bent_over_row', 'seated_cable_row'],
    cues: ['Hinge with a flat back', 'Pull the bar to the lower ribs'],
  }),
  ex({
    id: 'seated_cable_row',
    name: 'Seated Cable Row',
    pattern: 'pull_h',
    primary: ['upper_back', 'lats'],
    secondary: ['biceps', 'rear_delts'],
    equipment: ['cable'],
    level: 'beginner',
    subs: ['one_arm_dumbbell_row', 'machine_chest_supported_row'],
    cues: ['Sit tall', 'Pull the handle to the belly', 'Do not rock back'],
  }),
  ex({
    id: 'machine_chest_supported_row',
    name: 'Machine Chest-Supported Row',
    pattern: 'pull_h',
    primary: ['upper_back', 'lats'],
    secondary: ['rear_delts', 'biceps'],
    equipment: ['machine'],
    level: 'beginner',
    subs: ['chest_supported_dumbbell_row', 'seated_cable_row'],
    cues: ['Chest stays on the pad', 'Drive the elbows back'],
  }),
  ex({
    id: 'inverted_row',
    name: 'Inverted Row',
    pattern: 'pull_h',
    primary: ['upper_back', 'lats'],
    secondary: ['biceps', 'rear_delts', 'abs'],
    equipment: ['barbell', 'rack'],
    level: 'beginner',
    subs: ['doorframe_row', 'seated_cable_row'],
    cues: ['Bar set in a rack at waist height', 'Body straight, pull the chest to the bar'],
    loadable: false,
  }),
];

const PULL_V: Exercise[] = [
  ex({
    id: 'prone_lat_pulldown',
    name: 'Prone Floor Lat Pulldown',
    pattern: 'pull_v',
    primary: ['lats'],
    secondary: ['upper_back', 'rear_delts'],
    equipment: ['bodyweight'],
    level: 'beginner',
    subs: ['towel_lat_pulldown', 'dumbbell_pullover', 'lat_pulldown'],
    cues: ['Lie face down, arms overhead', 'Lift the arms and pull the elbows down to the ribs'],
    lowStimulus: true,
  }),
  ex({
    id: 'towel_lat_pulldown',
    name: 'Towel Lat Pulldown (Self-Resisted)',
    pattern: 'pull_v',
    primary: ['lats'],
    secondary: ['upper_back', 'biceps'],
    equipment: ['bodyweight'],
    level: 'beginner',
    subs: ['prone_lat_pulldown', 'dumbbell_pullover', 'lat_pulldown'],
    cues: [
      'Hold a towel overhead, hands wide',
      'Pull it hard apart and down behind the head, slowly',
    ],
    lowStimulus: true,
  }),
  ex({
    id: 'dumbbell_pullover',
    name: 'Dumbbell Pullover',
    pattern: 'pull_v',
    primary: ['lats', 'chest'],
    secondary: ['triceps'],
    equipment: ['dumbbells', 'bench'],
    level: 'intermediate',
    contra: ['shoulder'],
    subs: ['prone_lat_pulldown', 'straight_arm_pulldown', 'lat_pulldown'],
    cues: ['Upper back across the bench', 'Slight elbow bend', 'Lower only as far as comfortable'],
  }),
  ex({
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    pattern: 'pull_v',
    primary: ['lats'],
    secondary: ['biceps', 'upper_back'],
    equipment: ['cable'],
    level: 'beginner',
    subs: ['assisted_pull_up', 'pull_up', 'dumbbell_pullover', 'prone_lat_pulldown'],
    cues: ['Thighs under the pad', 'Pull the bar to the upper chest', 'Lean back slightly'],
  }),
  ex({
    id: 'pull_up',
    name: 'Pull-Up',
    pattern: 'pull_v',
    primary: ['lats'],
    secondary: ['biceps', 'upper_back', 'forearms'],
    equipment: ['pullup_bar'],
    level: 'intermediate',
    contra: ['shoulder'],
    subs: ['lat_pulldown', 'band_assisted_pull_up', 'negative_pull_up', 'chin_up'],
    cues: ['Overhand grip', 'Start from a dead hang', 'Chin over the bar'],
  }),
  ex({
    id: 'chin_up',
    name: 'Chin-Up',
    pattern: 'pull_v',
    primary: ['lats', 'biceps'],
    secondary: ['upper_back'],
    equipment: ['pullup_bar'],
    level: 'intermediate',
    contra: ['shoulder', 'elbow'],
    subs: ['pull_up', 'lat_pulldown'],
    cues: ['Underhand grip, shoulder-width', 'Pull the chest toward the bar'],
  }),
  ex({
    id: 'assisted_pull_up',
    name: 'Machine-Assisted Pull-Up',
    pattern: 'pull_v',
    primary: ['lats'],
    secondary: ['biceps', 'upper_back'],
    equipment: ['machine'],
    level: 'beginner',
    contra: ['shoulder'],
    subs: ['lat_pulldown', 'band_assisted_pull_up'],
    cues: ['More counterweight makes it easier', 'Full range of motion'],
    loadable: false,
  }),
  ex({
    id: 'band_assisted_pull_up',
    name: 'Band-Assisted Pull-Up',
    pattern: 'pull_v',
    primary: ['lats'],
    secondary: ['biceps', 'upper_back'],
    equipment: ['pullup_bar', 'bands'],
    level: 'beginner',
    contra: ['shoulder'],
    subs: ['assisted_pull_up', 'negative_pull_up', 'lat_pulldown'],
    cues: ['Loop the band over the bar, knee or foot in the band', 'Control the way down'],
  }),
  ex({
    id: 'negative_pull_up',
    name: 'Negative Pull-Up',
    pattern: 'pull_v',
    primary: ['lats'],
    secondary: ['biceps', 'upper_back', 'forearms'],
    equipment: ['pullup_bar'],
    level: 'beginner',
    contra: ['shoulder', 'elbow'],
    subs: ['band_assisted_pull_up', 'lat_pulldown'],
    cues: ['Jump or step to the top', 'Lower yourself over 3-5 seconds'],
  }),
  ex({
    id: 'straight_arm_pulldown',
    name: 'Straight-Arm Cable Pulldown',
    pattern: 'pull_v',
    primary: ['lats'],
    secondary: ['triceps', 'rear_delts'],
    equipment: ['cable'],
    level: 'beginner',
    subs: ['dumbbell_pullover', 'lat_pulldown'],
    cues: ['Arms almost straight', 'Sweep the bar down to the thighs'],
  }),
];

const CARRY: Exercise[] = [
  ex({
    id: 'bear_crawl',
    name: 'Bear Crawl',
    pattern: 'carry',
    primary: ['abs', 'front_delts'],
    secondary: ['quads', 'triceps'],
    equipment: ['bodyweight'],
    level: 'beginner',
    contra: ['wrist', 'shoulder'],
    subs: ['suitcase_carry', 'farmers_carry'],
    cues: ['Knees hover just above the floor', 'Move opposite hand and foot together', 'Back flat'],
    measure: 'seconds',
  }),
  ex({
    id: 'farmers_carry',
    name: "Farmer's Carry",
    pattern: 'carry',
    primary: ['forearms', 'traps'],
    secondary: ['abs', 'obliques'],
    equipment: ['dumbbells'],
    level: 'beginner',
    contra: ['neck'],
    subs: ['suitcase_carry', 'kettlebell_front_rack_carry', 'sled_push'],
    cues: ['Heavy dumbbells at your sides', 'Walk tall with short steps'],
    measure: 'seconds',
  }),
  ex({
    id: 'suitcase_carry',
    name: 'Suitcase Carry',
    pattern: 'carry',
    primary: ['obliques', 'forearms'],
    secondary: ['abs', 'traps'],
    equipment: ['dumbbells'],
    level: 'beginner',
    subs: ['farmers_carry', 'bear_crawl'],
    cues: ['One dumbbell, one side', 'Do not lean toward the weight'],
    measure: 'seconds',
    unilateral: true,
  }),
  ex({
    id: 'waiters_carry',
    name: "Waiter's Carry",
    pattern: 'carry',
    primary: ['front_delts', 'traps'],
    secondary: ['abs', 'obliques', 'triceps'],
    equipment: ['dumbbells'],
    level: 'intermediate',
    contra: ['shoulder', 'neck'],
    subs: ['suitcase_carry', 'farmers_carry'],
    cues: ['Dumbbell locked out overhead', 'Ribs down, walk slowly'],
    measure: 'seconds',
    unilateral: true,
  }),
  ex({
    id: 'kettlebell_front_rack_carry',
    name: 'Kettlebell Front-Rack Carry',
    pattern: 'carry',
    primary: ['abs', 'upper_back'],
    secondary: ['forearms', 'biceps'],
    equipment: ['kettlebell'],
    level: 'intermediate',
    contra: ['wrist'],
    subs: ['farmers_carry', 'suitcase_carry'],
    cues: ['Bells resting on the forearms at chest height', 'Stay upright'],
    measure: 'seconds',
  }),
  ex({
    id: 'sled_push',
    name: 'Sled Push',
    pattern: 'carry',
    primary: ['quads', 'glutes'],
    secondary: ['calves', 'abs'],
    equipment: ['machine'],
    level: 'beginner',
    contra: ['knee'],
    subs: ['farmers_carry', 'bear_crawl'],
    cues: ['Arms extended, body at an angle', 'Short, driving steps'],
    measure: 'seconds',
  }),
];

const CORE: Exercise[] = [
  ex({
    id: 'plank',
    name: 'Forearm Plank',
    pattern: 'core',
    primary: ['abs'],
    secondary: ['obliques', 'front_delts'],
    equipment: ['bodyweight'],
    level: 'beginner',
    subs: ['dead_bug', 'side_plank', 'cable_pallof_press'],
    cues: ['Elbows under the shoulders', 'Squeeze glutes, ribs down', 'Breathe'],
    measure: 'seconds',
  }),
  ex({
    id: 'side_plank',
    name: 'Side Plank',
    pattern: 'core',
    primary: ['obliques'],
    secondary: ['abs', 'glutes'],
    equipment: ['bodyweight'],
    level: 'beginner',
    contra: ['shoulder'],
    subs: ['plank', 'cable_pallof_press'],
    cues: ['Elbow under the shoulder', 'Hips high in a straight line'],
    measure: 'seconds',
    unilateral: true,
  }),
  ex({
    id: 'dead_bug',
    name: 'Dead Bug',
    pattern: 'core',
    primary: ['abs'],
    equipment: ['bodyweight'],
    level: 'beginner',
    subs: ['bird_dog', 'dumbbell_dead_bug', 'plank'],
    cues: ['Lower back pressed into the floor', 'Extend opposite arm and leg slowly'],
  }),
  ex({
    id: 'bird_dog',
    name: 'Bird Dog',
    pattern: 'core',
    primary: ['abs', 'lower_back'],
    secondary: ['glutes'],
    equipment: ['bodyweight'],
    level: 'beginner',
    subs: ['dead_bug', 'plank'],
    cues: ['On hands and knees', 'Reach opposite arm and leg long', 'Hips stay level'],
    unilateral: true,
  }),
  ex({
    id: 'hollow_body_hold',
    name: 'Hollow Body Hold',
    pattern: 'core',
    primary: ['abs'],
    equipment: ['bodyweight'],
    level: 'intermediate',
    contra: ['lower_back', 'neck'],
    subs: ['dead_bug', 'plank'],
    cues: ['Lower back glued to the floor', 'Bend the knees to make it easier'],
    measure: 'seconds',
  }),
  ex({
    id: 'reverse_crunch',
    name: 'Reverse Crunch',
    pattern: 'core',
    primary: ['abs'],
    secondary: ['obliques'],
    equipment: ['bodyweight'],
    level: 'beginner',
    contra: ['lower_back'],
    subs: ['dead_bug', 'hanging_knee_raise'],
    cues: ['Curl the hips off the floor', 'Lower slowly, no swinging'],
  }),
  ex({
    id: 'dumbbell_dead_bug',
    name: 'Dumbbell Dead Bug',
    pattern: 'core',
    primary: ['abs'],
    secondary: ['front_delts'],
    equipment: ['dumbbells'],
    level: 'beginner',
    subs: ['dead_bug', 'cable_pallof_press'],
    cues: ['Hold a light dumbbell above the chest', 'Lower back stays down'],
  }),
  ex({
    id: 'dumbbell_woodchop',
    name: 'Dumbbell Woodchop',
    pattern: 'core',
    primary: ['obliques'],
    secondary: ['abs', 'front_delts'],
    equipment: ['dumbbells'],
    level: 'intermediate',
    contra: ['lower_back'],
    subs: ['cable_pallof_press', 'side_plank'],
    cues: ['Rotate through the hips and torso together', 'Control the return'],
    unilateral: true,
  }),
  ex({
    id: 'cable_pallof_press',
    name: 'Cable Pallof Press',
    pattern: 'core',
    primary: ['obliques', 'abs'],
    equipment: ['cable'],
    level: 'beginner',
    subs: ['side_plank', 'dumbbell_dead_bug'],
    cues: ['Stand side-on to the cable', 'Press out and resist the rotation'],
    unilateral: true,
  }),
  ex({
    id: 'cable_crunch',
    name: 'Kneeling Cable Crunch',
    pattern: 'core',
    primary: ['abs'],
    secondary: ['obliques'],
    equipment: ['cable'],
    level: 'beginner',
    contra: ['lower_back', 'neck'],
    subs: ['reverse_crunch', 'dead_bug'],
    cues: ['Rope by the head', 'Curl the ribs toward the hips'],
  }),
  ex({
    id: 'hanging_knee_raise',
    name: 'Hanging Knee Raise',
    pattern: 'core',
    primary: ['abs'],
    secondary: ['obliques', 'forearms'],
    equipment: ['pullup_bar'],
    level: 'intermediate',
    contra: ['shoulder'],
    subs: ['reverse_crunch', 'cable_crunch'],
    cues: ['Dead hang, no swinging', 'Curl the pelvis up'],
  }),
];

const CARDIO: Exercise[] = [
  ex({
    id: 'jumping_jacks',
    name: 'Jumping Jacks',
    pattern: 'cardio',
    primary: ['calves'],
    secondary: ['quads', 'glutes', 'side_delts'],
    equipment: ['bodyweight'],
    level: 'beginner',
    contra: ['knee', 'ankle'],
    subs: ['step_jacks', 'stationary_bike'],
    cues: ['Land on the balls of the feet', 'Steady rhythm'],
    measure: 'seconds',
  }),
  ex({
    id: 'step_jacks',
    name: 'Step Jacks (Low-Impact)',
    pattern: 'cardio',
    primary: ['calves'],
    secondary: ['quads', 'glutes'],
    equipment: ['bodyweight'],
    level: 'beginner',
    subs: ['jumping_jacks', 'elliptical'],
    cues: ['Step out to the side while raising the arms', 'Keep a brisk pace'],
    measure: 'seconds',
  }),
  ex({
    id: 'burpee',
    name: 'Burpee',
    pattern: 'cardio',
    primary: ['quads', 'chest'],
    secondary: ['glutes', 'triceps', 'abs', 'front_delts'],
    equipment: ['bodyweight'],
    level: 'intermediate',
    contra: ['wrist', 'knee', 'shoulder', 'lower_back', 'hip', 'ankle'],
    subs: ['mountain_climber', 'step_jacks'],
    cues: ['Hands down, jump back to a plank', 'Step instead of jumping to make it easier'],
    measure: 'seconds',
  }),
  ex({
    id: 'mountain_climber',
    name: 'Mountain Climber',
    pattern: 'cardio',
    primary: ['abs'],
    secondary: ['quads', 'front_delts'],
    equipment: ['bodyweight'],
    level: 'beginner',
    contra: ['wrist', 'shoulder'],
    subs: ['step_jacks', 'burpee'],
    cues: ['Shoulders over the hands', 'Drive knees toward the chest quickly'],
    measure: 'seconds',
  }),
  ex({
    id: 'dumbbell_thruster',
    name: 'Dumbbell Thruster',
    pattern: 'cardio',
    primary: ['quads', 'front_delts'],
    secondary: ['glutes', 'triceps'],
    equipment: ['dumbbells'],
    level: 'intermediate',
    contra: ['knee', 'shoulder', 'lower_back'],
    subs: ['dumbbell_devil_press', 'burpee'],
    cues: ['Squat with dumbbells at the shoulders', 'Use the drive up to press overhead'],
    measure: 'seconds',
    loadable: true,
  }),
  ex({
    id: 'dumbbell_devil_press',
    name: 'Dumbbell Devil Press',
    pattern: 'cardio',
    primary: ['glutes', 'front_delts'],
    secondary: ['hamstrings', 'triceps', 'chest'],
    equipment: ['dumbbells'],
    level: 'advanced',
    contra: ['wrist', 'shoulder', 'lower_back'],
    subs: ['dumbbell_thruster', 'burpee'],
    cues: ['Burpee onto the dumbbells', 'Swing them overhead in one motion with a flat back'],
    measure: 'seconds',
    loadable: true,
  }),
  ex({
    id: 'rowing_machine',
    name: 'Rowing Machine',
    pattern: 'cardio',
    primary: ['upper_back', 'quads'],
    secondary: ['lats', 'glutes', 'hamstrings', 'biceps'],
    equipment: ['machine'],
    level: 'beginner',
    contra: ['lower_back'],
    subs: ['stationary_bike', 'elliptical'],
    cues: ['Legs, then body, then arms', 'Reverse the order on the way back'],
    measure: 'seconds',
  }),
  ex({
    id: 'stationary_bike',
    name: 'Stationary Bike',
    pattern: 'cardio',
    primary: ['quads'],
    secondary: ['glutes', 'calves', 'hamstrings'],
    equipment: ['machine'],
    level: 'beginner',
    subs: ['elliptical', 'incline_treadmill_walk'],
    cues: ['Saddle at hip height', 'Steady cadence, conversational pace'],
    measure: 'seconds',
  }),
  ex({
    id: 'incline_treadmill_walk',
    name: 'Incline Treadmill Walk',
    pattern: 'cardio',
    primary: ['glutes', 'calves'],
    secondary: ['quads', 'hamstrings'],
    equipment: ['machine'],
    level: 'beginner',
    subs: ['stationary_bike', 'step_jacks'],
    cues: ['Do not hold the handrails', 'Brisk pace you can talk at'],
    measure: 'seconds',
  }),
  ex({
    id: 'elliptical',
    name: 'Elliptical Trainer',
    pattern: 'cardio',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings', 'calves'],
    equipment: ['machine'],
    level: 'beginner',
    subs: ['stationary_bike', 'incline_treadmill_walk'],
    cues: ['Stand tall', 'Push and pull the handles'],
    measure: 'seconds',
  }),
];

const ISOLATION: Exercise[] = [
  ex({
    id: 'bodyweight_calf_raise',
    name: 'Bodyweight Calf Raise',
    pattern: 'isolation',
    primary: ['calves'],
    equipment: ['bodyweight'],
    level: 'beginner',
    contra: ['ankle'],
    subs: ['dumbbell_calf_raise', 'machine_calf_raise'],
    cues: ['Balls of the feet on a step', 'Full stretch at the bottom, pause at the top'],
  }),
  ex({
    id: 'bench_dip',
    name: 'Bench Dip',
    pattern: 'isolation',
    primary: ['triceps'],
    secondary: ['chest', 'front_delts'],
    equipment: ['bodyweight'],
    level: 'intermediate',
    contra: ['shoulder', 'wrist', 'elbow'],
    subs: ['dumbbell_overhead_triceps_extension', 'cable_triceps_pushdown'],
    cues: ['Hands on a sturdy chair behind you', 'Lower until elbows reach 90 degrees'],
  }),
  ex({
    id: 'prone_y_raise',
    name: 'Prone Y Raise',
    pattern: 'isolation',
    primary: ['rear_delts', 'traps'],
    secondary: ['upper_back'],
    equipment: ['bodyweight'],
    level: 'beginner',
    subs: ['dumbbell_rear_delt_fly', 'face_pull', 'band_pull_apart'],
    cues: ['Face down, arms in a Y', 'Lift the thumbs up and hold briefly'],
  }),
  ex({
    id: 'reverse_nordic',
    name: 'Reverse Nordic',
    pattern: 'isolation',
    primary: ['quads'],
    equipment: ['bodyweight'],
    level: 'intermediate',
    contra: ['knee'],
    subs: ['leg_extension'],
    cues: [
      'Kneel tall, lean back from the knees',
      'Keep hips extended, use a short range at first',
    ],
  }),
  ex({
    id: 'slider_leg_curl',
    name: 'Slider Leg Curl',
    pattern: 'isolation',
    primary: ['hamstrings'],
    secondary: ['glutes'],
    equipment: ['bodyweight'],
    level: 'intermediate',
    subs: ['seated_leg_curl'],
    cues: ['Heels on towels on a smooth floor', 'Hips up, curl the heels in'],
  }),
  ex({
    id: 'dumbbell_biceps_curl',
    name: 'Dumbbell Biceps Curl',
    pattern: 'isolation',
    primary: ['biceps'],
    secondary: ['forearms'],
    equipment: ['dumbbells'],
    level: 'beginner',
    contra: ['elbow'],
    subs: ['barbell_curl'],
    cues: ['Elbows by your sides', 'No swinging'],
  }),
  ex({
    id: 'dumbbell_lateral_raise',
    name: 'Dumbbell Lateral Raise',
    pattern: 'isolation',
    primary: ['side_delts'],
    secondary: ['traps'],
    equipment: ['dumbbells'],
    level: 'beginner',
    contra: ['shoulder'],
    subs: ['cable_lateral_raise'],
    cues: ['Slight bend in the elbows', 'Raise to shoulder height, no higher'],
  }),
  ex({
    id: 'dumbbell_overhead_triceps_extension',
    name: 'Dumbbell Overhead Triceps Extension',
    pattern: 'isolation',
    primary: ['triceps'],
    equipment: ['dumbbells'],
    level: 'beginner',
    contra: ['elbow', 'shoulder'],
    subs: ['cable_triceps_pushdown', 'bench_dip'],
    cues: ['Hold one dumbbell with both hands overhead', 'Elbows point forward'],
  }),
  ex({
    id: 'dumbbell_rear_delt_fly',
    name: 'Dumbbell Rear Delt Fly',
    pattern: 'isolation',
    primary: ['rear_delts'],
    secondary: ['upper_back'],
    equipment: ['dumbbells'],
    level: 'beginner',
    subs: ['prone_y_raise', 'face_pull'],
    cues: ['Hinge forward with a flat back', 'Lead with the elbows'],
  }),
  ex({
    id: 'dumbbell_calf_raise',
    name: 'Dumbbell Calf Raise',
    pattern: 'isolation',
    primary: ['calves'],
    equipment: ['dumbbells'],
    level: 'beginner',
    contra: ['ankle'],
    subs: ['bodyweight_calf_raise', 'machine_calf_raise'],
    cues: ['Dumbbells at your sides', 'Slow on the way down'],
  }),
  ex({
    id: 'dumbbell_fly',
    name: 'Dumbbell Fly',
    pattern: 'isolation',
    primary: ['chest'],
    secondary: ['front_delts'],
    equipment: ['dumbbells', 'bench'],
    level: 'intermediate',
    contra: ['shoulder'],
    subs: ['cable_fly'],
    cues: ['Soft elbows', 'Lower until you feel a chest stretch, not further'],
  }),
  ex({
    id: 'cable_triceps_pushdown',
    name: 'Cable Triceps Pushdown',
    pattern: 'isolation',
    primary: ['triceps'],
    equipment: ['cable'],
    level: 'beginner',
    contra: ['elbow'],
    subs: ['dumbbell_overhead_triceps_extension', 'bench_dip'],
    cues: ['Elbows pinned to the sides', 'Fully straighten the arms'],
  }),
  ex({
    id: 'leg_extension',
    name: 'Leg Extension',
    pattern: 'isolation',
    primary: ['quads'],
    equipment: ['machine'],
    level: 'beginner',
    contra: ['knee'],
    subs: ['reverse_nordic'],
    cues: ['Knee lined up with the machine pivot', 'Pause at the top'],
  }),
  ex({
    id: 'seated_leg_curl',
    name: 'Seated Leg Curl',
    pattern: 'isolation',
    primary: ['hamstrings'],
    equipment: ['machine'],
    level: 'beginner',
    subs: ['slider_leg_curl'],
    cues: ['Knee lined up with the pivot', 'Control the return'],
  }),
  ex({
    id: 'cable_lateral_raise',
    name: 'Cable Lateral Raise',
    pattern: 'isolation',
    primary: ['side_delts'],
    equipment: ['cable'],
    level: 'beginner',
    contra: ['shoulder'],
    subs: ['dumbbell_lateral_raise'],
    cues: ['Cable from the low pulley across the body', 'Raise to shoulder height'],
    unilateral: true,
  }),
  ex({
    id: 'face_pull',
    name: 'Cable Face Pull',
    pattern: 'isolation',
    primary: ['rear_delts', 'upper_back'],
    secondary: ['traps'],
    equipment: ['cable'],
    level: 'beginner',
    subs: ['dumbbell_rear_delt_fly', 'band_pull_apart', 'prone_y_raise'],
    cues: ['Rope at face height', 'Pull toward the eyes, elbows high'],
  }),
  ex({
    id: 'barbell_curl',
    name: 'Barbell Curl',
    pattern: 'isolation',
    primary: ['biceps'],
    secondary: ['forearms'],
    equipment: ['barbell'],
    level: 'beginner',
    contra: ['elbow', 'wrist'],
    subs: ['dumbbell_biceps_curl'],
    cues: ['Shoulder-width grip', 'Elbows still, no hip drive'],
  }),
  ex({
    id: 'machine_calf_raise',
    name: 'Machine Calf Raise',
    pattern: 'isolation',
    primary: ['calves'],
    equipment: ['machine'],
    level: 'beginner',
    contra: ['ankle'],
    subs: ['dumbbell_calf_raise', 'bodyweight_calf_raise'],
    cues: ['Full range of motion', 'Pause in the stretch'],
  }),
  ex({
    id: 'cable_fly',
    name: 'Cable Fly',
    pattern: 'isolation',
    primary: ['chest'],
    secondary: ['front_delts'],
    equipment: ['cable'],
    level: 'beginner',
    contra: ['shoulder'],
    subs: ['dumbbell_fly'],
    cues: ['Step forward from the cables', 'Hug a big tree'],
  }),
  ex({
    id: 'band_pull_apart',
    name: 'Band Pull-Apart',
    pattern: 'isolation',
    primary: ['rear_delts'],
    secondary: ['upper_back', 'traps'],
    equipment: ['bands'],
    level: 'beginner',
    subs: ['face_pull', 'prone_y_raise'],
    cues: ['Arms straight at shoulder height', 'Pull the band to the chest'],
  }),
];

/** The seed exercise catalog. */
export const EXERCISES: readonly Exercise[] = [
  ...SQUAT,
  ...LUNGE,
  ...HINGE,
  ...PUSH_H,
  ...PUSH_V,
  ...PULL_H,
  ...PULL_V,
  ...CARRY,
  ...CORE,
  ...CARDIO,
  ...ISOLATION,
];
